# Generated by Django 5.1.7 on 2025-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
