# Generated by Django 5.1.7 on 2025-03-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
