# Generated by Django 5.1.7 on 2025-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
