# Generated by Django 5.1.7 on 2025-03-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menucategory_menuitem_image_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu Categories'},
        ),
    ]
