# Generated by Django 5.1.7 on 2025-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
