# Generated by Django 5.1.7 on 2025-03-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_special_requests_orderitem_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
    ]
